package com.iamlegendz.hitforge.studio;

import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.graphics.Color;import android.view.*;import android.widget.*;import android.provider.OpenableColumns;import java.io.*;
import com.iamlegendz.hitforge.ai.*;import com.iamlegendz.hitforge.memory.*;import com.iamlegendz.hitforge.library.*;import com.iamlegendz.hitforge.quality.*;import com.iamlegendz.hitforge.export.*;import com.iamlegendz.hitforge.adapters.*;import com.iamlegendz.hitforge.model.*;

public final class HitforgeStudioActivity extends Activity {
 EditText idea,maxTokens,contextSize,temperature,teaching; Spinner forge,content; TextView output,status,memoryStatus,modelStatus,adapterStatus; PersonalMemoryStore memory; SongLibrary library; AdapterRegistry adapters; OfflineGenerationService service; File activeModel,activeAdapter; StringBuilder live=new StringBuilder();
 TextView tv(String s){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setPadding(16,8,16,8);return t;} Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);memory=new PersonalMemoryStore(this);library=new SongLibrary(this);adapters=new AdapterRegistry(this);service=new OfflineGenerationService(this);activeModel=ModelManager.active(this);String ap=adapters.activePath();activeAdapter=ap.isEmpty()?null:new File(ap);build();}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(16,16,16,16);root.setBackgroundColor(Color.rgb(10,10,14));root.addView(tv("HITFORGE • IAML3G3NDZ EDITION"));root.addView(tv("REAL LOCAL LLM • OFFLINE • PERSONAL AI • v1.1"));
  LinearLayout modelRow=new LinearLayout(this);Button importModel=btn("🤖 IMPORT GGUF");Button chooseModel=btn("MODEL");modelRow.addView(importModel,new LinearLayout.LayoutParams(0,-2,1));modelRow.addView(chooseModel,new LinearLayout.LayoutParams(0,-2,1));root.addView(modelRow);modelStatus=tv("");root.addView(modelStatus);
  LinearLayout adRow=new LinearLayout(this);Button importAd=btn("🧩 IMPORT LORA");Button chooseAd=btn("ADAPTER");adRow.addView(importAd,new LinearLayout.LayoutParams(0,-2,1));adRow.addView(chooseAd,new LinearLayout.LayoutParams(0,-2,1));root.addView(adRow);adapterStatus=tv("");root.addView(adapterStatus);
  forge=new Spinner(this);forge.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"IAML3G3NDZ","LEGEND","STREET","HEARTBREAK","COUNTRY SOUL","RAP BEAST","CINEMA","RADIO","DARK"}));root.addView(tv("FORGE MODE"));root.addView(forge);content=new Spinner(this);content.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"CLEAN","RADIO","MATURE","EXPLICIT LANGUAGE","DARK","HORROR","CRIME NOIR"}));root.addView(tv("CONTENT MODE"));root.addView(content);
  idea=new EditText(this);idea.setHint("Tell HITFORGE what to create...");root.addView(idea);LinearLayout knobs=new LinearLayout(this);maxTokens=new EditText(this);maxTokens.setHint("Tokens");maxTokens.setText("768");knobs.addView(maxTokens,new LinearLayout.LayoutParams(0,-2,1));contextSize=new EditText(this);contextSize.setHint("Context");contextSize.setText("4096");knobs.addView(contextSize,new LinearLayout.LayoutParams(0,-2,1));temperature=new EditText(this);temperature.setHint("Temp");temperature.setText("0.85");knobs.addView(temperature,new LinearLayout.LayoutParams(0,-2,1));root.addView(knobs);
  LinearLayout actions=new LinearLayout(this);Button create=btn("🔥 CREATE HIT");Button bigger=btn("⚡ BIGGER");actions.addView(create,new LinearLayout.LayoutParams(0,-2,1));actions.addView(bigger,new LinearLayout.LayoutParams(0,-2,1));root.addView(actions);
  Button accept=btn("⭐ ACCEPT & LEARN");Button analyze=btn("🎯 GOOSEBUMPS / HOOK ANALYZER");Button export=btn("📦 EXPORT APPROVED TRAINING DATA");Button libraryBtn=btn("📚 SONG LIBRARY");Button teach=btn("🧠 TEACH HITFORGE");root.addView(accept);root.addView(analyze);root.addView(export);root.addView(libraryBtn);root.addView(teach);
  memoryStatus=tv("");status=tv("OFFLINE • No INTERNET permission");root.addView(memoryStatus);root.addView(status);output=tv("");output.setTextIsSelectable(true);ScrollView sv=new ScrollView(this);sv.addView(output);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);refresh();
  importModel.setOnClickListener(v->pickModel());chooseModel.setOnClickListener(v->chooseModel());importAd.setOnClickListener(v->pickAdapter());chooseAd.setOnClickListener(v->chooseAdapter());create.setOnClickListener(v->generate(false));bigger.setOnClickListener(v->generate(true));accept.setOnClickListener(v->accept());analyze.setOnClickListener(v->analyze());export.setOnClickListener(v->exportTraining());libraryBtn.setOnClickListener(v->Toast.makeText(this,"Saved songs: "+library.count(),Toast.LENGTH_LONG).show());teach.setOnClickListener(v->teach());}
 void refresh(){modelStatus.setText(activeModel==null?"MODEL: none — import a local .gguf":"MODEL: "+activeModel.getName());adapterStatus.setText(activeAdapter==null?"ADAPTER: base model only":"ADAPTER: "+activeAdapter.getName());memoryStatus.setText("MEMORY • accepted: "+memory.approvedExamples().length()+" • preferences: "+memory.preferenceCount()+" • songs: "+library.count());}
 void pickModel(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/octet-stream");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,101);}
 void pickAdapter(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/octet-stream");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,102);}
 String name(Uri u,String fallback){CursorHolder h=new CursorHolder();try{android.database.Cursor q=getContentResolver().query(u,null,null,null,null);if(q!=null){int n=q.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(q.moveToFirst()&&n>=0)h.v=q.getString(n);q.close();}}catch(Exception ignored){}return h.v.isEmpty()?fallback:h.v;} static final class CursorHolder{String v="";}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null||d.getData()==null)return;try{Uri u=d.getData();if(r==101){activeModel=ModelManager.importUri(this,u,name(u,"model.gguf"));ModelManager.setActive(this,activeModel);inspectModel();}else if(r==102){File ad=new File(getFilesDir(),"adapters");if(!ad.exists())ad.mkdirs();String n=name(u,"adapter.gguf").replaceAll("[^A-Za-z0-9._-]","_");if(!n.toLowerCase().endsWith(".gguf"))n+=".gguf";File out=new File(ad,n);try(InputStream in=getContentResolver().openInputStream(u);OutputStream os=new FileOutputStream(out)){byte[] buf=new byte[1024*1024];int z;while((z=in.read(buf))!=-1)os.write(buf,0,z);}if(activeModel!=null){String info=LocalLlmBridge.nativeAdapterInfo(activeModel.getAbsolutePath(),out.getAbsolutePath());adapters.register(n,out.getAbsolutePath(),activeModel.getName(),info,"imported");adapters.setActive(n);activeAdapter=out;}refresh();Toast.makeText(this,"LoRA imported and activated locally.",Toast.LENGTH_LONG).show();}}catch(Exception e){Toast.makeText(this,"Import failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 void inspectModel(){if(!LocalLlmBridge.modelLooksUsable(activeModel)){status.setText("MODEL: invalid GGUF");return;}try{status.setText("OFFLINE MODEL INSPECT\n"+LocalLlmBridge.nativeModelInfo(activeModel.getAbsolutePath()));}catch(Throwable t){status.setText("Native runtime unavailable: "+t.getMessage());}refresh();}
 void chooseModel(){String[] ms=ModelManager.installed(this);if(ms.length==0){Toast.makeText(this,"Import a GGUF first.",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("SELECT OFFLINE MODEL").setItems(ms,(d,w)->{activeModel=new File(ModelManager.modelDir(this),ms[w]);ModelManager.setActive(this,activeModel);inspectModel();}).show();}
 void chooseAdapter(){org.json.JSONArray a=adapters.all();if(a.length()==0){Toast.makeText(this,"No LoRA adapters imported.",Toast.LENGTH_SHORT).show();return;}String[] names=new String[a.length()+1];names[0]="BASE MODEL ONLY";for(int i=0;i<a.length();i++)names[i+1]=a.optJSONObject(i).optString("name");new AlertDialog.Builder(this).setTitle("SELECT ADAPTER").setItems(names,(d,w)->{if(w==0){activeAdapter=null;adapters.setActive("__none__");}else{String n=names[w];adapters.setActive(n);String p=adapters.activePath();activeAdapter=p.isEmpty()?null:new File(p);}refresh();}).show();}
 void generate(boolean bigger){if(activeModel==null){Toast.makeText(this,"Import/select a GGUF model first.",Toast.LENGTH_LONG).show();return;}String q=idea.getText().toString().trim();if(q.isEmpty())q="Create an unforgettable song about turning struggle into power.";if(bigger)q="Make this concept dramatically bigger: stronger hook, sharper imagery, deeper emotional payoff, cinematic build, and a final chorus designed for replay. Preserve the original identity.\n"+q;String prompt=SongDirector.build(q,forge.getSelectedItem().toString(),content.getSelectedItem().toString(),memory.preferenceContext(),memory.retrieve(q,8));int mt=parseInt(maxTokens.getText().toString(),768),ctx=parseInt(contextSize.getText().toString(),4096); String guard=DevicePreflight.checkModel(this,activeModel,ctx); if(!guard.isEmpty()){Toast.makeText(this,guard,Toast.LENGTH_LONG).show(); return;}float temp=parseFloat(temperature.getText().toString(),0.85f);live.setLength(0);output.setText("HITFORGE IS FORGING...\n\n");status.setText("OFFLINE • GENERATING • adapter="+(activeAdapter==null?"base":activeAdapter.getName()));service.generate(activeModel,activeAdapter,prompt,mt,ctx,temp,(int)(System.nanoTime()&0x7fffffff),new OfflineGenerationService.Callback(){public void token(String piece){runOnUiThread(()->{live.append(piece);output.setText(live.toString());});}public void done(String text){runOnUiThread(()->{if(live.length()==0||!text.equals(live.toString()))output.setText(text);status.setText("OFFLINE • COMPLETE • tokens streamed locally");});}});}
 void accept(){String out=output.getText().toString().trim();if(out.isEmpty()||out.startsWith("HITFORGE IS FORGING"))return;memory.addExample("accepted",idea.getText().toString(),out,"Accepted by user");library.saveSong(idea.getText().toString(),idea.getText().toString(),out,forge.getSelectedItem().toString(),content.getSelectedItem().toString());refresh();Toast.makeText(this,"Accepted. HITFORGE can now retrieve this example locally.",Toast.LENGTH_SHORT).show();}
 void teach(){final EditText e=new EditText(this);e.setHint("Example: shorter hooks, denser internal rhymes, darker imagery...");new AlertDialog.Builder(this).setTitle("TEACH HITFORGE").setView(e).setPositiveButton("LEARN",(d,w)->{String s=e.getText().toString().trim();if(!s.isEmpty())memory.teach(s,8);refresh();}).setNegativeButton("CANCEL",null).show();}
 void analyze(){HookAnalyzer.Report r=HookAnalyzer.analyze(output.getText().toString());new AlertDialog.Builder(this).setTitle("GOOSEBUMPS / HOOK ANALYZER").setMessage(r.toString()).setPositiveButton("OK",null).show();}
 void exportTraining(){try{File f=TrainingDatasetExporter.exportApproved(this,memory.approvedExamples());Toast.makeText(this,"Exported "+memory.approvedExamples().length()+" approved examples to "+f.getAbsolutePath(),Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Export failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 int parseInt(String s,int d){try{return Integer.parseInt(s);}catch(Exception e){return d;}}float parseFloat(String s,float d){try{return Float.parseFloat(s);}catch(Exception e){return d;}}@Override protected void onDestroy(){service.shutdown();super.onDestroy();}
}
